export type MeaningMode = "auto" | "synonym" | "related" | "broader" | "narrower" | "antonym" | "imagery" | "rephrasing";
export type SemanticInputKind = "word" | "phrase";
export type MeaningRelationship = "synonym" | "near-synonym" | "related-concept" | "broader-concept" | "narrower-concept" | "antonym" | "symbolic-association" | "imagery-association" | "rephrasing";
export type MeaningSource = "thesaurus" | "wordnet" | "datamuse" | "phrase-library" | "embedding-index" | "generated" | "combined";
export type SemanticSense = { id: string; definition: string; partOfSpeech?: string; examples?: string[]; keywords?: string[]; confidence: number; source: string };
export type InputAnalysis = { originalText: string; normalizedText: string; tokens: string[]; inputKind: SemanticInputKind; wordCount: number; detectedPartOfSpeech?: string; possibleSenses: SemanticSense[]; selectedSense?: SemanticSense };
export type MeaningScoreBreakdown = { embeddingSimilarity: number; lexicalRelationship: number; contextualSimilarity: number; toneSimilarity: number; imagerySimilarity: number; grammaticalCompatibility: number; specificityCompatibility: number; lexicalOverlapPenalty: number; quality: number; diversityValue: number; total: number };
export type MeaningResult = { id: string; text: string; normalizedText: string; inputKind: SemanticInputKind; relationship: MeaningRelationship; parentRelationship?: MeaningRelationship; score: number; strength: number; scoreBreakdown: MeaningScoreBreakdown; definition?: string; explanation: string; example?: string; tone?: string; partOfSpeech?: string; source: MeaningSource; sourceDetails?: string[]; parentText?: string; possibleSenseId?: string; parentSimilarity?: number; centerSimilarity?: number };
export type MeaningSearchRequest = { query: string; mode?: MeaningMode; limit?: number; minimumScore?: number; exclude?: string[]; context?: string; senseId?: string; originalCenter?: string; originalSenseId?: string };
export type MeaningSearchResponse = { center: { text: string; inputKind: SemanticInputKind; analysis: InputAnalysis }; mode: MeaningMode; results: MeaningResult[]; diagnostics: { candidateCount: number; scoredCount: number; returnedCount: number; cacheHit: boolean; durationMs: number; embeddingProvider: string; warnings: string[] } };
export interface EmbeddingProvider { readonly name: string; embed(texts: string[]): Promise<number[][]>; dimensions(): number }
export type LexicalCandidate = { text: string; relationship?: MeaningRelationship; definition?: string; partOfSpeech?: string; senseId?: string; oppositeGroup?: string; confidence?: number; sources: MeaningSource[]; explanation?: string; example?: string; toneTags?: string[]; imageryTags?: string[]; conceptTags?: string[]; grammaticalShape?: string; quality?: number; vector?: number[]; similarity?: number };
export interface LexicalProvider { findSenses(word: string): Promise<SemanticSense[]>; findRelations(word: string, options: { senseId?: string; relations: Array<"synonym" | "broader" | "narrower" | "antonym" | "related">; limit: number }): Promise<LexicalCandidate[]> }
export type PhraseEntry = { id: string; text: string; normalizedText: string; embedding?: number[]; definition?: string; explanation?: string; example?: string; partOfSpeech?: string; grammaticalShape?: string; toneTags: string[]; imageryTags: string[]; conceptTags: string[]; quality: number; source: string; symbolicFor?: string[]; rephrasingFor?: string[] };
export interface SemanticVectorIndex { search(vector: number[], options: { limit: number; minimumSimilarity?: number; filters?: Record<string, string | string[]> }): Promise<Array<{ id: string; similarity: number }>> }
export interface SemanticGenerator { generateCandidates(input: { query: string; mode: MeaningMode; analysis: InputAnalysis; count: number }): Promise<Array<{ text: string; explanation?: string }>> }
export type MeaningNodeData = { relationship: MeaningRelationship; scoreBreakdown: MeaningScoreBreakdown; explanation: string; possibleSenseId?: string; sourceDetails?: string[]; parentSimilarity?: number; centerSimilarity?: number; parentText?: string };
